#178 - Using exclusive storage access on metadata copy
artipie/maven-adapter pull request #179
Opened 2020-09-02 14:49 UTC by olegmoz

Closes #178 
Using exclusive storage access on metadata copy

2020-09-02 15:23 UTC, g4s8 requested changes
@olegmoz please check one minor comment

2020-09-02 15:23 UTC, g4s8 commented on src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
> +            "Storage has no locks",
@olegmoz it's a test failure message, so it describes negative scenario, e.g. `"Storage has locks"`

2020-09-03 07:32 UTC, olegmoz commented on src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
> +            "Storage has no locks",
@g4s8 thanks for pointing at that. After adding this check I noticed that some of exceptions are not about locks and point to a bug in ASTO, see https://github.com/artipie/asto/issues/260 

Going to fix it and then come back to this PR.

2020-09-09 08:43 UTC, olegmoz commented on src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
> +            "Storage has no locks",
@g4s8 fixed the problem with locks and improved tests, please review

2020-09-10 08:37 UTC, olegmoz commented
@olenagerasimova could you please review this issue?

2020-09-10 09:04 UTC, g4s8 approved these changes
@olegmoz thanks

2020-09-10 09:05 UTC, merged

2020-09-10 09:25 UTC, 0crat commented
Job `gh:artipie/maven-adapter#179` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/34d12351-22b3-4b38-9a5f-3bb1777a6e49, version: 0.54.5, hash: ${buildNumber} -->