#219 - Fix MavenProxySlice response
artipie/maven-adapter pull request #220
Opened 2020-10-26 07:54 UTC by genryxy

Closes #219 
Fix `MavenProxySlice` response when not found

2020-10-29 13:01 UTC, olegmoz requested changes

2020-10-29 13:01 UTC, olegmoz commented on src/main/java/com/artipie/maven/http/CachedProxySlice.java
> +                        }
@genryxy the problem with this code right now is that you are reading whole content for every request into memory, including `.jar` files which might be quite large. It is possible to handle response status and not read content at all, as it is done in PyPi adapter: https://github.com/artipie/pypi-adapter/blob/master/src/main/java/com/artipie/pypi/http/ProxySlice.java

2020-10-30 14:03 UTC, genryxy commented
@olegmoz thanks, added puzzle to change implementation. I tried the similar approach as in pypi-adapter, but `MavenProxySliceAuthIT#shouldGet` hangs. Probably it happens because cache in pypi-adapter is wrapped in `FromRemoteCache` or maybe there is problem with requests. I was not able to identify the source of problem.

2020-10-30 14:18 UTC, olegmoz approved these changes
@genryxy thanks, merging

2020-10-30 14:18 UTC, merged

2020-10-30 15:02 UTC, 0crat commented
Job `gh:artipie/maven-adapter#220` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e12d977c-ce63-4d45-a699-a87e724dfb7d, version: 0.54.5, hash: ${buildNumber} -->